// Generated by `npm run art`: do not edit by hand.
// Beast sprites available in public/sprites (closed mouth), those with an open-mouth version,
// and card illustrations in public/art.
export const SPRITE_KEYS: readonly string[] = [
  'barracuda',
  'coccodrillo_marino',
  'coccodrillo_marino_leggendario',
  'megattera',
  'orca',
  'orca_matriarca',
  'orca_matriarca_finale',
  'orca_preistorica_albina',
  'sfregiato',
  'squalo_bianco',
  'squalo_bianco_albino',
  'squalo_bianco_albino_finale',
  'squalo_bianco_alfa',
  'squalo_bianco_finale',
  'squalo_martello',
  'squalo_tigre',
  'tartaruga_marina',
  'torpedine',
];

export const OPEN_SPRITE_KEYS: readonly string[] = [
  'barracuda',
  'coccodrillo_marino',
  'coccodrillo_marino_leggendario',
  'megattera',
  'orca',
  'orca_matriarca',
  'orca_matriarca_finale',
  'orca_preistorica_albina',
  'sfregiato',
  'squalo_bianco',
  'squalo_bianco_albino',
  'squalo_bianco_albino_finale',
  'squalo_bianco_alfa',
  'squalo_bianco_finale',
  'squalo_martello',
  'squalo_tigre',
  'tartaruga_marina',
];

export const ART_KEYS: readonly string[] = [
  'barracuda',
  'coccodrillo_marino',
  'coccodrillo_marino_leggendario',
  'megattera',
  'orca',
  'orca_matriarca',
  'orca_matriarca_finale',
  'orca_preistorica_albina',
  'sfregiato',
  'squalo_bianco',
  'squalo_bianco_albino',
  'squalo_bianco_albino_finale',
  'squalo_bianco_alfa',
  'squalo_bianco_finale',
  'squalo_martello',
  'squalo_tigre',
  'tartaruga_marina',
  'torpedine',
];

// Three-quarter battle pictures (<id>_front for the wild one, <id>_back for yours, + _open).
export const BATTLE_ART_KEYS: readonly string[] = [];
